{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "195496e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib as mpl\n",
    "import sklearn\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import train_test_split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b35889da",
   "metadata": {},
   "outputs": [],
   "source": [
    "years = ['2022']\n",
    "months = ['01','02','03','04','05','06','07','08','09','10','11','12']\n",
    "\n",
    "arr = ['202302','202301']\n",
    "\n",
    "for year in years:\n",
    "    for month in months:\n",
    "        arr.append(year+month)\n",
    "\n",
    "dfs = []\n",
    "\n",
    "for i in arr:\n",
    "    df = pd.read_csv(f'house{i}.csv',encoding= 'cp949')\n",
    "    dfs.append(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c8f4fea9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[                시군구   전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   84.9450  202302   25,500   4  1997.0\n",
       " 1       강원도 강릉시 견소동   84.9450  202302   16,000   1  1997.0\n",
       " 2       강원도 강릉시 견소동   84.9450  202302   23,000   1  1997.0\n",
       " 3       강원도 강릉시 견소동   84.9900  202302   29,000   6  2005.0\n",
       " 4        강원도 강릉시 교동  164.0098  202302   59,500  12  2009.0\n",
       " ...             ...       ...     ...      ...  ..     ...\n",
       " 32600  충청북도 충주시 호암동   84.9289  202302   23,000   1  2007.0\n",
       " 32601  충청북도 충주시 호암동   84.9289  202302   23,000   7  2007.0\n",
       " 32602  충청북도 충주시 호암동   84.6800  202302   20,800   3  2002.0\n",
       " 32603  충청북도 충주시 호암동   84.9500  202302   40,000  16  2019.0\n",
       " 32604  충청북도 충주시 호암동   99.8000  202302   49,000  11  2019.0\n",
       " \n",
       " [32605 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   84.930  202301   25,000   6  1997.0\n",
       " 1       강원도 강릉시 견소동   84.990  202301   29,800   8  2005.0\n",
       " 2       강원도 강릉시 견소동   84.990  202301   28,500   5  2005.0\n",
       " 3        강원도 강릉시 교동   59.860  202301   20,000  11  2002.0\n",
       " 4        강원도 강릉시 교동   59.840  202301   25,000   3  2002.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 20014  충청북도 충주시 호암동   84.809  202301   33,000   4  2019.0\n",
       " 20015  충청북도 충주시 호암동   84.809  202301   33,000   4  2019.0\n",
       " 20016  충청북도 충주시 호암동   84.960  202301   38,500  19  2019.0\n",
       " 20017  충청북도 충주시 호암동   84.890  202301   37,000   4  2019.0\n",
       " 20018  충청북도 충주시 호암동   84.960  202301   40,800  18  2019.0\n",
       " \n",
       " [20019 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   59.800  202201   20,000   8  1997.0\n",
       " 1       강원도 강릉시 견소동   43.380  202201   12,900   4  1997.0\n",
       " 2       강원도 강릉시 견소동   84.945  202201   26,700   6  1997.0\n",
       " 3       강원도 강릉시 견소동   84.990  202201   35,000   3  2005.0\n",
       " 4       강원도 강릉시 견소동   59.990  202201   24,700   5  2005.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 22539  충청북도 충주시 호암동   84.950  202201   47,000  20  2019.0\n",
       " 22540  충청북도 충주시 호암동   84.950  202201   45,000   5  2019.0\n",
       " 22541  충청북도 충주시 호암동   84.950  202201   47,000  18  2019.0\n",
       " 22542  충청북도 충주시 호암동   84.940  202201   47,800   8  2019.0\n",
       " 22543  충청북도 충주시 호암동   99.870  202201   55,700  20  2019.0\n",
       " \n",
       " [22544 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   59.800  202202   22,700  13  1997.0\n",
       " 1       강원도 강릉시 견소동   59.800  202202   19,300  13  1997.0\n",
       " 2       강원도 강릉시 견소동   84.945  202202   27,800  15  1997.0\n",
       " 3       강원도 강릉시 견소동   59.800  202202   21,000  12  1997.0\n",
       " 4       강원도 강릉시 견소동   59.990  202202   32,000  11  2005.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 24529  충청북도 충주시 호암동   84.960  202202   47,500  11  2019.0\n",
       " 24530  충청북도 충주시 호암동   84.890  202202   47,200  13  2019.0\n",
       " 24531  충청북도 충주시 호암동   84.890  202202   47,000  12  2019.0\n",
       " 24532  충청북도 충주시 호암동  120.490  202202   65,000  11  2019.0\n",
       " 24533  충청북도 충주시 호암동   84.960  202202   53,500  20  2019.0\n",
       " \n",
       " [24534 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   59.800  202203   18,000   3  1997.0\n",
       " 1       강원도 강릉시 견소동   59.800  202203   21,000   8  1997.0\n",
       " 2       강원도 강릉시 견소동   84.945  202203   25,500  10  1997.0\n",
       " 3       강원도 강릉시 견소동   84.990  202203   33,500   1  2005.0\n",
       " 4       강원도 강릉시 견소동   59.990  202203   27,000  13  2005.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 31718  충청북도 충주시 호암동   99.870  202203   55,500   4  2019.0\n",
       " 31719  충청북도 충주시 호암동  120.490  202203   69,000  19  2019.0\n",
       " 31720  충청북도 충주시 호암동   84.950  202203   47,800  20  2019.0\n",
       " 31721  충청북도 충주시 호암동   84.890  202203   48,800  24  2019.0\n",
       " 31722  충청북도 충주시 호암동   99.800  202203   51,000  15  2019.0\n",
       " \n",
       " [31723 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   59.800  202204   22,000  15  1997.0\n",
       " 1       강원도 강릉시 견소동   59.800  202204   21,500   2  1997.0\n",
       " 2       강원도 강릉시 견소동   84.945  202204   26,000   6  1997.0\n",
       " 3       강원도 강릉시 견소동   59.990  202204   28,000   5  2005.0\n",
       " 4       강원도 강릉시 견소동   59.990  202204   29,200   9  2005.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 36051  충청북도 충주시 호암동   84.680  202204   18,200   1  2002.0\n",
       " 36052  충청북도 충주시 호암동  111.760  202204   59,700   1  2019.0\n",
       " 36053  충청북도 충주시 호암동   99.870  202204   55,500   4  2019.0\n",
       " 36054  충청북도 충주시 호암동   99.800  202204   51,000   1  2019.0\n",
       " 36055  충청북도 충주시 호암동  111.760  202204   59,700   1  2019.0\n",
       " \n",
       " [36056 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층  건축년도\n",
       " 0       강원도 강릉시 견소동   39.080  202205   16,000  10  1997\n",
       " 1       강원도 강릉시 견소동   84.945  202205   26,700  13  1997\n",
       " 2       강원도 강릉시 견소동   84.990  202205   33,800  14  2005\n",
       " 3       강원도 강릉시 견소동   84.990  202205   33,700   3  2005\n",
       " 4       강원도 강릉시 견소동   84.990  202205   30,000   2  2005\n",
       " ...             ...      ...     ...      ...  ..   ...\n",
       " 32308  충청북도 충주시 호암동   77.946  202205   38,000   1  2019\n",
       " 32309  충청북도 충주시 호암동   59.840  202205    7,000   5  1994\n",
       " 32310  충청북도 충주시 호암동   59.760  202205   12,000  10  1994\n",
       " 32311  충청북도 충주시 호암동   84.680  202205   19,800   1  2002\n",
       " 32312  충청북도 충주시 호암동   84.940  202205   50,000  10  2019\n",
       " \n",
       " [32313 rows x 6 columns],\n",
       "                 시군구   전용면적(㎡)    계약년월 거래금액(만원)   층  건축년도\n",
       " 0       강원도 강릉시 견소동   59.8000  202206   23,000   8  1997\n",
       " 1       강원도 강릉시 견소동   39.0800  202206   15,800   6  1997\n",
       " 2       강원도 강릉시 견소동   59.9900  202206   29,600  15  2005\n",
       " 3       강원도 강릉시 견소동   84.9900  202206   35,800   6  2005\n",
       " 4        강원도 강릉시 교동  135.1727  202206   61,000  13  2009\n",
       " ...             ...       ...     ...      ...  ..   ...\n",
       " 23788  충청북도 충주시 호암동  111.7600  202206   59,700   1  2019\n",
       " 23789  충청북도 충주시 호암동   99.8000  202206   51,000   4  2019\n",
       " 23790  충청북도 충주시 호암동  120.4900  202206   58,000  12  2019\n",
       " 23791  충청북도 충주시 호암동  120.4900  202206   67,000   7  2019\n",
       " 23792  충청북도 충주시 호암동   84.9500  202206   49,000  10  2019\n",
       " \n",
       " [23793 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동    43.38  202207   16,000   9  1997.0\n",
       " 1       강원도 강릉시 견소동    59.80  202207   22,900  12  1997.0\n",
       " 2       강원도 강릉시 견소동    84.99  202207   33,500   3  2005.0\n",
       " 3       강원도 강릉시 견소동    84.99  202207   36,000  10  2005.0\n",
       " 4        강원도 강릉시 교동    84.97  202207   46,700  14  1999.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 18551  충청북도 충주시 호암동    51.75  202207    4,700   5  1998.0\n",
       " 18552  충청북도 충주시 호암동    51.75  202207    4,700  11  1998.0\n",
       " 18553  충청북도 충주시 호암동    51.75  202207    4,500   1  1998.0\n",
       " 18554  충청북도 충주시 호암동    51.75  202207    4,700   4  1998.0\n",
       " 18555  충청북도 충주시 호암동    59.76  202207   13,300  14  1994.0\n",
       " \n",
       " [18556 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층  건축년도\n",
       " 0       강원도 강릉시 견소동   84.945  202208   26,000   1  1997\n",
       " 1       강원도 강릉시 견소동   43.380  202208   16,500  12  1997\n",
       " 2       강원도 강릉시 견소동   59.990  202208   28,500  13  2005\n",
       " 3       강원도 강릉시 견소동   84.990  202208   36,000   9  2005\n",
       " 4       강원도 강릉시 견소동   59.990  202208   27,000   7  2005\n",
       " ...             ...      ...     ...      ...  ..   ...\n",
       " 17797  충청북도 충주시 호암동   76.430  202208   14,300  10  1994\n",
       " 17798  충청북도 충주시 호암동   76.430  202208   10,000   6  1994\n",
       " 17799  충청북도 충주시 호암동   77.946  202208   37,000   3  2019\n",
       " 17800  충청북도 충주시 호암동   66.957  202208   36,000  11  2019\n",
       " 17801  충청북도 충주시 호암동   84.803  202208   43,500  16  2019\n",
       " \n",
       " [17802 rows x 6 columns],\n",
       "                 시군구   전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   39.0800  202209   17,700  10  1997.0\n",
       " 1       강원도 강릉시 견소동   84.9900  202209   37,500   8  2005.0\n",
       " 2       강원도 강릉시 견소동   59.9900  202209   31,500  11  2005.0\n",
       " 3        강원도 강릉시 교동   84.9866  202209   28,000   1  2009.0\n",
       " 4        강원도 강릉시 교동   59.8900  202209   30,000  14  1999.0\n",
       " ...             ...       ...     ...      ...  ..     ...\n",
       " 16457  충청북도 충주시 호암동  119.9180  202209   60,000  23  2019.0\n",
       " 16458  충청북도 충주시 호암동   84.6800  202209   21,300   5  2002.0\n",
       " 16459  충청북도 충주시 호암동   84.6800  202209   19,500  13  2002.0\n",
       " 16460  충청북도 충주시 호암동   84.6800  202209   19,500  13  2002.0\n",
       " 16461  충청북도 충주시 호암동   99.8000  202209   51,000   5  2019.0\n",
       " \n",
       " [16462 rows x 6 columns],\n",
       "                 시군구  전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동  84.9900  202210   35,000  10  2005.0\n",
       " 1        강원도 강릉시 교동  84.9855  202210   49,900  11  2009.0\n",
       " 2        강원도 강릉시 교동  84.8400  202210   37,400   9  1999.0\n",
       " 3        강원도 강릉시 교동  54.8100  202210   12,000   4  1985.0\n",
       " 4        강원도 강릉시 교동  49.9200  202210   18,000  11  1999.0\n",
       " ...             ...      ...     ...      ...  ..     ...\n",
       " 17238  충청북도 충주시 호암동  56.8800  202210    8,000   2  1989.0\n",
       " 17239  충청북도 충주시 호암동  84.9672  202210   42,800   3  2019.0\n",
       " 17240  충청북도 충주시 호암동  84.8090  202210   40,800   4  2019.0\n",
       " 17241  충청북도 충주시 호암동  84.9600  202210   16,500   9  1994.0\n",
       " 17242  충청북도 충주시 호암동  84.6800  202210   20,300   8  2002.0\n",
       " \n",
       " [17243 rows x 6 columns],\n",
       "                 시군구   전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   59.9900  202211   26,000   2  2005.0\n",
       " 1        강원도 강릉시 교동  118.0686  202211   47,000   3  2009.0\n",
       " 2        강원도 강릉시 교동  118.0686  202211   52,000  15  2009.0\n",
       " 3        강원도 강릉시 교동   59.8400  202211   11,000   2  1997.0\n",
       " 4        강원도 강릉시 교동   84.7155  202211   40,000  12  2006.0\n",
       " ...             ...       ...     ...      ...  ..     ...\n",
       " 16048  충청북도 충주시 호암동   51.7500  202211    4,700   4  1998.0\n",
       " 16049  충청북도 충주시 호암동   51.7500  202211    4,700   6  1998.0\n",
       " 16050  충청북도 충주시 호암동  119.9180  202211   62,000  17  2019.0\n",
       " 16051  충청북도 충주시 호암동   66.9570  202211   31,000   9  2019.0\n",
       " 16052  충청북도 충주시 호암동   84.6800  202211   22,100  12  2002.0\n",
       " \n",
       " [16053 rows x 6 columns],\n",
       "                 시군구   전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       " 0       강원도 강릉시 견소동   84.9900  202212   34,100  12  2005.0\n",
       " 1        강원도 강릉시 교동   59.4900  202212    8,300   4  1985.0\n",
       " 2        강원도 강릉시 교동   59.7400  202212   26,500  13  2002.0\n",
       " 3        강원도 강릉시 교동   59.8400  202212   10,000   5  1997.0\n",
       " 4        강원도 강릉시 교동   40.8600  202212    6,700   2  1988.0\n",
       " ...             ...       ...     ...      ...  ..     ...\n",
       " 15425  충청북도 충주시 호암동   84.8030  202212   39,300  23  2019.0\n",
       " 15426  충청북도 충주시 호암동   84.9600  202212   17,500   2  1994.0\n",
       " 15427  충청북도 충주시 호암동   84.9289  202212   23,500   4  2007.0\n",
       " 15428  충청북도 충주시 호암동   84.9400  202212   40,000  11  2019.0\n",
       " 15429  충청북도 충주시 호암동  120.4900  202212   55,000   2  2019.0\n",
       " \n",
       " [15430 rows x 6 columns]]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "dfs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9fcdd453",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_df = pd.DataFrame()\n",
    "for df in dfs:\n",
    "    total_df = pd.concat([total_df,df])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ea57476b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>시군구</th>\n",
       "      <th>전용면적(㎡)</th>\n",
       "      <th>계약년월</th>\n",
       "      <th>거래금액(만원)</th>\n",
       "      <th>층</th>\n",
       "      <th>건축년도</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>강원도 강릉시 견소동</td>\n",
       "      <td>84.9450</td>\n",
       "      <td>202302</td>\n",
       "      <td>25,500</td>\n",
       "      <td>4</td>\n",
       "      <td>1997.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>강원도 강릉시 견소동</td>\n",
       "      <td>84.9450</td>\n",
       "      <td>202302</td>\n",
       "      <td>16,000</td>\n",
       "      <td>1</td>\n",
       "      <td>1997.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>강원도 강릉시 견소동</td>\n",
       "      <td>84.9450</td>\n",
       "      <td>202302</td>\n",
       "      <td>23,000</td>\n",
       "      <td>1</td>\n",
       "      <td>1997.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>강원도 강릉시 견소동</td>\n",
       "      <td>84.9900</td>\n",
       "      <td>202302</td>\n",
       "      <td>29,000</td>\n",
       "      <td>6</td>\n",
       "      <td>2005.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>강원도 강릉시 교동</td>\n",
       "      <td>164.0098</td>\n",
       "      <td>202302</td>\n",
       "      <td>59,500</td>\n",
       "      <td>12</td>\n",
       "      <td>2009.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15425</th>\n",
       "      <td>충청북도 충주시 호암동</td>\n",
       "      <td>84.8030</td>\n",
       "      <td>202212</td>\n",
       "      <td>39,300</td>\n",
       "      <td>23</td>\n",
       "      <td>2019.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15426</th>\n",
       "      <td>충청북도 충주시 호암동</td>\n",
       "      <td>84.9600</td>\n",
       "      <td>202212</td>\n",
       "      <td>17,500</td>\n",
       "      <td>2</td>\n",
       "      <td>1994.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15427</th>\n",
       "      <td>충청북도 충주시 호암동</td>\n",
       "      <td>84.9289</td>\n",
       "      <td>202212</td>\n",
       "      <td>23,500</td>\n",
       "      <td>4</td>\n",
       "      <td>2007.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15428</th>\n",
       "      <td>충청북도 충주시 호암동</td>\n",
       "      <td>84.9400</td>\n",
       "      <td>202212</td>\n",
       "      <td>40,000</td>\n",
       "      <td>11</td>\n",
       "      <td>2019.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15429</th>\n",
       "      <td>충청북도 충주시 호암동</td>\n",
       "      <td>120.4900</td>\n",
       "      <td>202212</td>\n",
       "      <td>55,000</td>\n",
       "      <td>2</td>\n",
       "      <td>2019.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>325133 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                시군구   전용면적(㎡)    계약년월 거래금액(만원)   층    건축년도\n",
       "0       강원도 강릉시 견소동   84.9450  202302   25,500   4  1997.0\n",
       "1       강원도 강릉시 견소동   84.9450  202302   16,000   1  1997.0\n",
       "2       강원도 강릉시 견소동   84.9450  202302   23,000   1  1997.0\n",
       "3       강원도 강릉시 견소동   84.9900  202302   29,000   6  2005.0\n",
       "4        강원도 강릉시 교동  164.0098  202302   59,500  12  2009.0\n",
       "...             ...       ...     ...      ...  ..     ...\n",
       "15425  충청북도 충주시 호암동   84.8030  202212   39,300  23  2019.0\n",
       "15426  충청북도 충주시 호암동   84.9600  202212   17,500   2  1994.0\n",
       "15427  충청북도 충주시 호암동   84.9289  202212   23,500   4  2007.0\n",
       "15428  충청북도 충주시 호암동   84.9400  202212   40,000  11  2019.0\n",
       "15429  충청북도 충주시 호암동  120.4900  202212   55,000   2  2019.0\n",
       "\n",
       "[325133 rows x 6 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8da146b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_df['큰지역'] = total_df['시군구'].apply(lambda x:x.split()[0])\n",
    "total_df['세부지역'] = total_df['시군구'].apply(lambda x:x.split()[1])\n",
    "total_df.drop(columns='시군구', inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1ac9b643",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_df = total_df[['거래금액(만원)','전용면적(㎡)','계약년월','층','건축년도','큰지역','세부지역'] ]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "65a72785",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 325133 entries, 0 to 15429\n",
      "Data columns (total 7 columns):\n",
      " #   Column    Non-Null Count   Dtype  \n",
      "---  ------    --------------   -----  \n",
      " 0   거래금액(만원)  325133 non-null  object \n",
      " 1   전용면적(㎡)   325133 non-null  float64\n",
      " 2   계약년월      325133 non-null  int64  \n",
      " 3   층         325133 non-null  int64  \n",
      " 4   건축년도      325097 non-null  float64\n",
      " 5   큰지역       325133 non-null  object \n",
      " 6   세부지역      325133 non-null  object \n",
      "dtypes: float64(2), int64(2), object(3)\n",
      "memory usage: 19.8+ MB\n"
     ]
    }
   ],
   "source": [
    "total_df.info() # 건축년도에 36개 null 존재"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "967b83b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_df = total_df.dropna(axis=0) #null 제거"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5a6fcd88",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 325097 entries, 0 to 15429\n",
      "Data columns (total 7 columns):\n",
      " #   Column    Non-Null Count   Dtype  \n",
      "---  ------    --------------   -----  \n",
      " 0   거래금액(만원)  325097 non-null  object \n",
      " 1   전용면적(㎡)   325097 non-null  float64\n",
      " 2   계약년월      325097 non-null  int64  \n",
      " 3   층         325097 non-null  int64  \n",
      " 4   건축년도      325097 non-null  float64\n",
      " 5   큰지역       325097 non-null  object \n",
      " 6   세부지역      325097 non-null  object \n",
      "dtypes: float64(2), int64(2), object(3)\n",
      "memory usage: 19.8+ MB\n"
     ]
    }
   ],
   "source": [
    "total_df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "0089585c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0        25,500\n",
       "1        16,000\n",
       "2        23,000\n",
       "3        29,000\n",
       "4        59,500\n",
       "          ...  \n",
       "15425    39,300\n",
       "15426    17,500\n",
       "15427    23,500\n",
       "15428    40,000\n",
       "15429    55,000\n",
       "Name: 거래금액(만원), Length: 325097, dtype: object"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "total_df['거래금액(만원)'] # ,때문에 type이 object로 나옴"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "f606e865",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'int' object has no attribute 'split'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[50], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[43mtotal_df\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m거래금액(만원)\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mapply\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43;01mlambda\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mx\u001b[49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msplit\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m,\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msplit\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m,\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msplit\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m,\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m>\u001b[39;49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m  \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msplit\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m,\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;66;03m# ,제거 object -> int\u001b[39;00m\n\u001b[1;32m      2\u001b[0m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m]\u001b[38;5;241m.\u001b[39mastype(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mint\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m      3\u001b[0m total_df\u001b[38;5;241m.\u001b[39minfo()\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/pandas/core/series.py:4771\u001b[0m, in \u001b[0;36mSeries.apply\u001b[0;34m(self, func, convert_dtype, args, **kwargs)\u001b[0m\n\u001b[1;32m   4661\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mapply\u001b[39m(\n\u001b[1;32m   4662\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   4663\u001b[0m     func: AggFuncType,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   4666\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs,\n\u001b[1;32m   4667\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m DataFrame \u001b[38;5;241m|\u001b[39m Series:\n\u001b[1;32m   4668\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   4669\u001b[0m \u001b[38;5;124;03m    Invoke function on values of Series.\u001b[39;00m\n\u001b[1;32m   4670\u001b[0m \n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   4769\u001b[0m \u001b[38;5;124;03m    dtype: float64\u001b[39;00m\n\u001b[1;32m   4770\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m-> 4771\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mSeriesApply\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mconvert_dtype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mapply\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/pandas/core/apply.py:1123\u001b[0m, in \u001b[0;36mSeriesApply.apply\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1120\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mapply_str()\n\u001b[1;32m   1122\u001b[0m \u001b[38;5;66;03m# self.f is Callable\u001b[39;00m\n\u001b[0;32m-> 1123\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mapply_standard\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/pandas/core/apply.py:1174\u001b[0m, in \u001b[0;36mSeriesApply.apply_standard\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1172\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   1173\u001b[0m         values \u001b[38;5;241m=\u001b[39m obj\u001b[38;5;241m.\u001b[39mastype(\u001b[38;5;28mobject\u001b[39m)\u001b[38;5;241m.\u001b[39m_values\n\u001b[0;32m-> 1174\u001b[0m         mapped \u001b[38;5;241m=\u001b[39m \u001b[43mlib\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmap_infer\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1175\u001b[0m \u001b[43m            \u001b[49m\u001b[43mvalues\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1176\u001b[0m \u001b[43m            \u001b[49m\u001b[43mf\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1177\u001b[0m \u001b[43m            \u001b[49m\u001b[43mconvert\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconvert_dtype\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1178\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1180\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(mapped) \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(mapped[\u001b[38;5;241m0\u001b[39m], ABCSeries):\n\u001b[1;32m   1181\u001b[0m     \u001b[38;5;66;03m# GH#43986 Need to do list(mapped) in order to get treated as nested\u001b[39;00m\n\u001b[1;32m   1182\u001b[0m     \u001b[38;5;66;03m#  See also GH#25959 regarding EA support\u001b[39;00m\n\u001b[1;32m   1183\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m obj\u001b[38;5;241m.\u001b[39m_constructor_expanddim(\u001b[38;5;28mlist\u001b[39m(mapped), index\u001b[38;5;241m=\u001b[39mobj\u001b[38;5;241m.\u001b[39mindex)\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/pandas/_libs/lib.pyx:2924\u001b[0m, in \u001b[0;36mpandas._libs.lib.map_infer\u001b[0;34m()\u001b[0m\n",
      "Cell \u001b[0;32mIn[50], line 1\u001b[0m, in \u001b[0;36m<lambda>\u001b[0;34m(x)\u001b[0m\n\u001b[0;32m----> 1\u001b[0m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m]\u001b[38;5;241m.\u001b[39mapply(\u001b[38;5;28;01mlambda\u001b[39;00m x: x\u001b[38;5;241m.\u001b[39msplit(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m,\u001b[39m\u001b[38;5;124m'\u001b[39m)[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;241m+\u001b[39m x\u001b[38;5;241m.\u001b[39msplit(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m,\u001b[39m\u001b[38;5;124m'\u001b[39m)[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(\u001b[43mx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msplit\u001b[49m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m,\u001b[39m\u001b[38;5;124m'\u001b[39m)) \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m2\u001b[39m  \u001b[38;5;28;01melse\u001b[39;00m x\u001b[38;5;241m.\u001b[39msplit(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m,\u001b[39m\u001b[38;5;124m'\u001b[39m)[\u001b[38;5;241m0\u001b[39m]) \u001b[38;5;66;03m# ,제거 object -> int\u001b[39;00m\n\u001b[1;32m      2\u001b[0m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m total_df[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m거래금액(만원)\u001b[39m\u001b[38;5;124m'\u001b[39m]\u001b[38;5;241m.\u001b[39mastype(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mint\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m      3\u001b[0m total_df\u001b[38;5;241m.\u001b[39minfo()\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'int' object has no attribute 'split'"
     ]
    }
   ],
   "source": [
    "total_df['거래금액(만원)'] = total_df['거래금액(만원)'].apply(lambda x: x.split(',')[0] + x.split(',')[1] if len(x.split(',')) >= 2  else x.split(',')[0]) # ,제거 object -> int\n",
    "total_df['거래금액(만원)'] = total_df['거래금액(만원)'].astype('int')\n",
    "total_df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40f14d0f",
   "metadata": {},
   "outputs": [],
   "source": [
    "total_df['큰지역'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 81,
   "id": "e4063238",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 79600 entries, 1068 to 10433\n",
      "Data columns (total 7 columns):\n",
      " #   Column    Non-Null Count  Dtype  \n",
      "---  ------    --------------  -----  \n",
      " 0   거래금액(만원)  79600 non-null  int64  \n",
      " 1   전용면적(㎡)   79600 non-null  float64\n",
      " 2   계약년월      79600 non-null  int64  \n",
      " 3   층         79600 non-null  int64  \n",
      " 4   건축년도      79600 non-null  float64\n",
      " 5   큰지역       79600 non-null  object \n",
      " 6   세부지역      79600 non-null  object \n",
      "dtypes: float64(2), int64(3), object(2)\n",
      "memory usage: 4.9+ MB\n"
     ]
    }
   ],
   "source": [
    "local_GS = (total_df.큰지역=='경기도') | (total_df.큰지역=='서울특별시')\n",
    "GS_df = total_df[local_GS]\n",
    "GS_df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 82,
   "id": "a6941e76",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>거래금액(만원)</th>\n",
       "      <th>전용면적(㎡)</th>\n",
       "      <th>계약년월</th>\n",
       "      <th>층</th>\n",
       "      <th>건축년도</th>\n",
       "      <th>큰지역</th>\n",
       "      <th>세부지역</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1068</th>\n",
       "      <td>6000</td>\n",
       "      <td>59.4900</td>\n",
       "      <td>202302</td>\n",
       "      <td>6</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>가평군</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1070</th>\n",
       "      <td>17850</td>\n",
       "      <td>84.8420</td>\n",
       "      <td>202302</td>\n",
       "      <td>2</td>\n",
       "      <td>2007.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>가평군</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1071</th>\n",
       "      <td>7000</td>\n",
       "      <td>75.3600</td>\n",
       "      <td>202302</td>\n",
       "      <td>1</td>\n",
       "      <td>1991.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>가평군</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1072</th>\n",
       "      <td>32700</td>\n",
       "      <td>127.9437</td>\n",
       "      <td>202302</td>\n",
       "      <td>2</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>가평군</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1073</th>\n",
       "      <td>20700</td>\n",
       "      <td>59.8700</td>\n",
       "      <td>202302</td>\n",
       "      <td>13</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>가평군</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3952</th>\n",
       "      <td>34500</td>\n",
       "      <td>84.8578</td>\n",
       "      <td>202212</td>\n",
       "      <td>6</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>화성시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3953</th>\n",
       "      <td>33000</td>\n",
       "      <td>84.8578</td>\n",
       "      <td>202212</td>\n",
       "      <td>6</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>화성시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3954</th>\n",
       "      <td>39500</td>\n",
       "      <td>84.9730</td>\n",
       "      <td>202212</td>\n",
       "      <td>12</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>화성시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3955</th>\n",
       "      <td>43000</td>\n",
       "      <td>84.9870</td>\n",
       "      <td>202212</td>\n",
       "      <td>20</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>화성시</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3956</th>\n",
       "      <td>33600</td>\n",
       "      <td>84.9560</td>\n",
       "      <td>202212</td>\n",
       "      <td>9</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>경기도</td>\n",
       "      <td>화성시</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>62981 rows × 7 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      거래금액(만원)   전용면적(㎡)    계약년월   층    건축년도  큰지역 세부지역\n",
       "1068      6000   59.4900  202302   6  1992.0  경기도  가평군\n",
       "1070     17850   84.8420  202302   2  2007.0  경기도  가평군\n",
       "1071      7000   75.3600  202302   1  1991.0  경기도  가평군\n",
       "1072     32700  127.9437  202302   2  2008.0  경기도  가평군\n",
       "1073     20700   59.8700  202302  13  2018.0  경기도  가평군\n",
       "...        ...       ...     ...  ..     ...  ...  ...\n",
       "3952     34500   84.8578  202212   6  2008.0  경기도  화성시\n",
       "3953     33000   84.8578  202212   6  2008.0  경기도  화성시\n",
       "3954     39500   84.9730  202212  12  2008.0  경기도  화성시\n",
       "3955     43000   84.9870  202212  20  2008.0  경기도  화성시\n",
       "3956     33600   84.9560  202212   9  2008.0  경기도  화성시\n",
       "\n",
       "[62981 rows x 7 columns]"
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_df[GS_df.큰지역 == '경기도']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "id": "841da0f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/0r/1nt20vf52jx576xwtk9wl2lw0000gn/T/ipykernel_15025/2711072175.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.\n",
      "  GS_df.corr(method = 'pearson')\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>거래금액(만원)</th>\n",
       "      <th>전용면적(㎡)</th>\n",
       "      <th>계약년월</th>\n",
       "      <th>층</th>\n",
       "      <th>건축년도</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>거래금액(만원)</th>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.523338</td>\n",
       "      <td>0.030970</td>\n",
       "      <td>0.181920</td>\n",
       "      <td>0.040460</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>전용면적(㎡)</th>\n",
       "      <td>0.523338</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.066849</td>\n",
       "      <td>0.141407</td>\n",
       "      <td>0.024048</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>계약년월</th>\n",
       "      <td>0.030970</td>\n",
       "      <td>0.066849</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.083440</td>\n",
       "      <td>0.108917</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>층</th>\n",
       "      <td>0.181920</td>\n",
       "      <td>0.141407</td>\n",
       "      <td>0.083440</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.287387</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>건축년도</th>\n",
       "      <td>0.040460</td>\n",
       "      <td>0.024048</td>\n",
       "      <td>0.108917</td>\n",
       "      <td>0.287387</td>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          거래금액(만원)   전용면적(㎡)      계약년월         층      건축년도\n",
       "거래금액(만원)  1.000000  0.523338  0.030970  0.181920  0.040460\n",
       "전용면적(㎡)   0.523338  1.000000  0.066849  0.141407  0.024048\n",
       "계약년월      0.030970  0.066849  1.000000  0.083440  0.108917\n",
       "층         0.181920  0.141407  0.083440  1.000000  0.287387\n",
       "건축년도      0.040460  0.024048  0.108917  0.287387  1.000000"
      ]
     },
     "execution_count": 83,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_df.corr(method = 'pearson')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 84,
   "id": "a067f5a1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Int64Index: 79600 entries, 1068 to 10433\n",
      "Data columns (total 7 columns):\n",
      " #   Column    Non-Null Count  Dtype  \n",
      "---  ------    --------------  -----  \n",
      " 0   거래금액(만원)  79600 non-null  int64  \n",
      " 1   전용면적(㎡)   79600 non-null  float64\n",
      " 2   계약년월      79600 non-null  int64  \n",
      " 3   층         79600 non-null  int64  \n",
      " 4   건축년도      79600 non-null  float64\n",
      " 5   큰지역       79600 non-null  object \n",
      " 6   세부지역      79600 non-null  object \n",
      "dtypes: float64(2), int64(3), object(2)\n",
      "memory usage: 4.9+ MB\n"
     ]
    }
   ],
   "source": [
    "GS_df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "56d89e7f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/0r/1nt20vf52jx576xwtk9wl2lw0000gn/T/ipykernel_15025/631463283.py:2: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  GS_df['큰지역'] = GS_df['큰지역'].map(mapping_dict)\n",
      "/var/folders/0r/1nt20vf52jx576xwtk9wl2lw0000gn/T/ipykernel_15025/631463283.py:71: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  GS_df['세부지역'] = GS_df['세부지역'].map(mapping_dict)\n"
     ]
    }
   ],
   "source": [
    "mapping_dict = {'경기도': 0, '서울특별시': 1}\n",
    "GS_df['큰지역'] = GS_df['큰지역'].map(mapping_dict)\n",
    "\n",
    "mapping_dict = {'가평군': 0,\n",
    " '고양덕양구': 1,\n",
    " '고양일산동구': 2,\n",
    " '고양일산서구': 3,\n",
    " '과천시': 4,\n",
    " '광명시': 5,\n",
    " '광주시': 6,\n",
    " '구리시': 7,\n",
    " '군포시': 8,\n",
    " '김포시': 9,\n",
    " '남양주시': 10,\n",
    " '동두천시': 11,\n",
    " '부천시': 12,\n",
    " '성남분당구': 13,\n",
    " '성남수정구': 14,\n",
    " '성남중원구': 15,\n",
    " '수원권선구': 16,\n",
    " '수원영통구': 17,\n",
    " '수원장안구': 18,\n",
    " '수원팔달구': 19,\n",
    " '시흥시': 20,\n",
    " '안산단원구': 21,\n",
    " '안산상록구': 22,\n",
    " '안성시': 23,\n",
    " '안양동안구': 24,\n",
    " '안양만안구': 25,\n",
    " '양주시': 26,\n",
    " '양평군': 27,\n",
    " '여주시': 28,\n",
    " '연천군': 29,\n",
    " '오산시': 30,\n",
    " '용인기흥구': 31,\n",
    " '용인수지구': 32,\n",
    " '용인처인구': 33,\n",
    " '의왕시': 34,\n",
    " '의정부시': 35,\n",
    " '이천시': 36,\n",
    " '파주시': 37,\n",
    " '평택시': 38,\n",
    " '포천시': 39,\n",
    " '하남시': 40,\n",
    " '화성시': 41,\n",
    " '강남구': 42,\n",
    " '강동구': 43,\n",
    " '강북구': 44,\n",
    " '강서구': 45,\n",
    " '관악구': 46,\n",
    " '광진구': 47,\n",
    " '구로구': 48,\n",
    " '금천구': 49,\n",
    " '노원구': 50,\n",
    " '도봉구': 51,\n",
    " '동대문구': 52,\n",
    " '동작구': 53,\n",
    " '마포구': 54,\n",
    " '서대문구': 55,\n",
    " '서초구': 56,\n",
    " '성동구': 57,\n",
    " '성북구': 58,\n",
    " '송파구': 59,\n",
    " '양천구': 60,\n",
    " '영등포구': 61,\n",
    " '용산구': 62,\n",
    " '은평구': 63,\n",
    " '종로구': 64,\n",
    " '중구': 65,\n",
    " '중랑구': 66}\n",
    "GS_df['세부지역'] = GS_df['세부지역'].map(mapping_dict)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "e5366061",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1068      0\n",
       "1070      0\n",
       "1071      0\n",
       "1072      0\n",
       "1073      0\n",
       "         ..\n",
       "10429    66\n",
       "10430    66\n",
       "10431    66\n",
       "10432    66\n",
       "10433    66\n",
       "Name: 세부지역, Length: 79600, dtype: int64"
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_df['세부지역']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "76f20965",
   "metadata": {},
   "outputs": [],
   "source": [
    "GS_df.to_csv(\"/Users/kangminje/Documents/houseprice/temp.csv\", mode='w', encoding=\"utf-8-sig\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "e0dfa2e8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>큰지역_경기도</th>\n",
       "      <th>큰지역_서울특별시</th>\n",
       "      <th>세부지역_가평군</th>\n",
       "      <th>세부지역_강남구</th>\n",
       "      <th>세부지역_강동구</th>\n",
       "      <th>세부지역_강북구</th>\n",
       "      <th>세부지역_강서구</th>\n",
       "      <th>세부지역_고양덕양구</th>\n",
       "      <th>세부지역_고양일산동구</th>\n",
       "      <th>세부지역_고양일산서구</th>\n",
       "      <th>...</th>\n",
       "      <th>세부지역_의정부시</th>\n",
       "      <th>세부지역_이천시</th>\n",
       "      <th>세부지역_종로구</th>\n",
       "      <th>세부지역_중구</th>\n",
       "      <th>세부지역_중랑구</th>\n",
       "      <th>세부지역_파주시</th>\n",
       "      <th>세부지역_평택시</th>\n",
       "      <th>세부지역_포천시</th>\n",
       "      <th>세부지역_하남시</th>\n",
       "      <th>세부지역_화성시</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1068</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1070</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1071</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1072</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1073</th>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10429</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10430</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10431</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10432</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10433</th>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>79600 rows × 69 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       큰지역_경기도  큰지역_서울특별시  세부지역_가평군  세부지역_강남구  세부지역_강동구  세부지역_강북구  세부지역_강서구  \\\n",
       "1068         1          0         1         0         0         0         0   \n",
       "1070         1          0         1         0         0         0         0   \n",
       "1071         1          0         1         0         0         0         0   \n",
       "1072         1          0         1         0         0         0         0   \n",
       "1073         1          0         1         0         0         0         0   \n",
       "...        ...        ...       ...       ...       ...       ...       ...   \n",
       "10429        0          1         0         0         0         0         0   \n",
       "10430        0          1         0         0         0         0         0   \n",
       "10431        0          1         0         0         0         0         0   \n",
       "10432        0          1         0         0         0         0         0   \n",
       "10433        0          1         0         0         0         0         0   \n",
       "\n",
       "       세부지역_고양덕양구  세부지역_고양일산동구  세부지역_고양일산서구  ...  세부지역_의정부시  세부지역_이천시  \\\n",
       "1068            0            0            0  ...          0         0   \n",
       "1070            0            0            0  ...          0         0   \n",
       "1071            0            0            0  ...          0         0   \n",
       "1072            0            0            0  ...          0         0   \n",
       "1073            0            0            0  ...          0         0   \n",
       "...           ...          ...          ...  ...        ...       ...   \n",
       "10429           0            0            0  ...          0         0   \n",
       "10430           0            0            0  ...          0         0   \n",
       "10431           0            0            0  ...          0         0   \n",
       "10432           0            0            0  ...          0         0   \n",
       "10433           0            0            0  ...          0         0   \n",
       "\n",
       "       세부지역_종로구  세부지역_중구  세부지역_중랑구  세부지역_파주시  세부지역_평택시  세부지역_포천시  세부지역_하남시  \\\n",
       "1068          0        0         0         0         0         0         0   \n",
       "1070          0        0         0         0         0         0         0   \n",
       "1071          0        0         0         0         0         0         0   \n",
       "1072          0        0         0         0         0         0         0   \n",
       "1073          0        0         0         0         0         0         0   \n",
       "...         ...      ...       ...       ...       ...       ...       ...   \n",
       "10429         0        0         1         0         0         0         0   \n",
       "10430         0        0         1         0         0         0         0   \n",
       "10431         0        0         1         0         0         0         0   \n",
       "10432         0        0         1         0         0         0         0   \n",
       "10433         0        0         1         0         0         0         0   \n",
       "\n",
       "       세부지역_화성시  \n",
       "1068          0  \n",
       "1070          0  \n",
       "1071          0  \n",
       "1072          0  \n",
       "1073          0  \n",
       "...         ...  \n",
       "10429         0  \n",
       "10430         0  \n",
       "10431         0  \n",
       "10432         0  \n",
       "10433         0  \n",
       "\n",
       "[79600 rows x 69 columns]"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_ohe = pd.get_dummies(GS_df[['큰지역','세부지역']])\n",
    "GS_ohe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "6e7bcd90",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>거래금액(만원)</th>\n",
       "      <th>전용면적(㎡)</th>\n",
       "      <th>계약년월</th>\n",
       "      <th>층</th>\n",
       "      <th>건축년도</th>\n",
       "      <th>큰지역_경기도</th>\n",
       "      <th>큰지역_서울특별시</th>\n",
       "      <th>세부지역_가평군</th>\n",
       "      <th>세부지역_강남구</th>\n",
       "      <th>세부지역_강동구</th>\n",
       "      <th>...</th>\n",
       "      <th>세부지역_의정부시</th>\n",
       "      <th>세부지역_이천시</th>\n",
       "      <th>세부지역_종로구</th>\n",
       "      <th>세부지역_중구</th>\n",
       "      <th>세부지역_중랑구</th>\n",
       "      <th>세부지역_파주시</th>\n",
       "      <th>세부지역_평택시</th>\n",
       "      <th>세부지역_포천시</th>\n",
       "      <th>세부지역_하남시</th>\n",
       "      <th>세부지역_화성시</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1068</th>\n",
       "      <td>6000</td>\n",
       "      <td>59.4900</td>\n",
       "      <td>202302</td>\n",
       "      <td>6</td>\n",
       "      <td>1992.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1070</th>\n",
       "      <td>17850</td>\n",
       "      <td>84.8420</td>\n",
       "      <td>202302</td>\n",
       "      <td>2</td>\n",
       "      <td>2007.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1071</th>\n",
       "      <td>7000</td>\n",
       "      <td>75.3600</td>\n",
       "      <td>202302</td>\n",
       "      <td>1</td>\n",
       "      <td>1991.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1072</th>\n",
       "      <td>32700</td>\n",
       "      <td>127.9437</td>\n",
       "      <td>202302</td>\n",
       "      <td>2</td>\n",
       "      <td>2008.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1073</th>\n",
       "      <td>20700</td>\n",
       "      <td>59.8700</td>\n",
       "      <td>202302</td>\n",
       "      <td>13</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10429</th>\n",
       "      <td>19500</td>\n",
       "      <td>22.7000</td>\n",
       "      <td>202212</td>\n",
       "      <td>12</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10430</th>\n",
       "      <td>19500</td>\n",
       "      <td>22.7000</td>\n",
       "      <td>202212</td>\n",
       "      <td>12</td>\n",
       "      <td>2019.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10431</th>\n",
       "      <td>15300</td>\n",
       "      <td>15.3100</td>\n",
       "      <td>202212</td>\n",
       "      <td>17</td>\n",
       "      <td>2018.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10432</th>\n",
       "      <td>13900</td>\n",
       "      <td>14.8550</td>\n",
       "      <td>202212</td>\n",
       "      <td>7</td>\n",
       "      <td>2014.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10433</th>\n",
       "      <td>40200</td>\n",
       "      <td>59.4000</td>\n",
       "      <td>202212</td>\n",
       "      <td>12</td>\n",
       "      <td>1993.0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>79600 rows × 74 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       거래금액(만원)   전용면적(㎡)    계약년월   층    건축년도  큰지역_경기도  큰지역_서울특별시  세부지역_가평군  \\\n",
       "1068       6000   59.4900  202302   6  1992.0        1          0         1   \n",
       "1070      17850   84.8420  202302   2  2007.0        1          0         1   \n",
       "1071       7000   75.3600  202302   1  1991.0        1          0         1   \n",
       "1072      32700  127.9437  202302   2  2008.0        1          0         1   \n",
       "1073      20700   59.8700  202302  13  2018.0        1          0         1   \n",
       "...         ...       ...     ...  ..     ...      ...        ...       ...   \n",
       "10429     19500   22.7000  202212  12  2019.0        0          1         0   \n",
       "10430     19500   22.7000  202212  12  2019.0        0          1         0   \n",
       "10431     15300   15.3100  202212  17  2018.0        0          1         0   \n",
       "10432     13900   14.8550  202212   7  2014.0        0          1         0   \n",
       "10433     40200   59.4000  202212  12  1993.0        0          1         0   \n",
       "\n",
       "       세부지역_강남구  세부지역_강동구  ...  세부지역_의정부시  세부지역_이천시  세부지역_종로구  세부지역_중구  \\\n",
       "1068          0         0  ...          0         0         0        0   \n",
       "1070          0         0  ...          0         0         0        0   \n",
       "1071          0         0  ...          0         0         0        0   \n",
       "1072          0         0  ...          0         0         0        0   \n",
       "1073          0         0  ...          0         0         0        0   \n",
       "...         ...       ...  ...        ...       ...       ...      ...   \n",
       "10429         0         0  ...          0         0         0        0   \n",
       "10430         0         0  ...          0         0         0        0   \n",
       "10431         0         0  ...          0         0         0        0   \n",
       "10432         0         0  ...          0         0         0        0   \n",
       "10433         0         0  ...          0         0         0        0   \n",
       "\n",
       "       세부지역_중랑구  세부지역_파주시  세부지역_평택시  세부지역_포천시  세부지역_하남시  세부지역_화성시  \n",
       "1068          0         0         0         0         0         0  \n",
       "1070          0         0         0         0         0         0  \n",
       "1071          0         0         0         0         0         0  \n",
       "1072          0         0         0         0         0         0  \n",
       "1073          0         0         0         0         0         0  \n",
       "...         ...       ...       ...       ...       ...       ...  \n",
       "10429         1         0         0         0         0         0  \n",
       "10430         1         0         0         0         0         0  \n",
       "10431         1         0         0         0         0         0  \n",
       "10432         1         0         0         0         0         0  \n",
       "10433         1         0         0         0         0         0  \n",
       "\n",
       "[79600 rows x 74 columns]"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_with_ohe = pd.concat([GS_df, GS_ohe], axis = 1) #one hot encoding\n",
    "GS_with_ohe.drop(columns=['큰지역','세부지역'], inplace=True)\n",
    "GS_with_ohe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "0d78cdb0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['거래금액(만원)', '전용면적(㎡)', '계약년월', '층', '건축년도', '큰지역_경기도', '큰지역_서울특별시',\n",
       "       '세부지역_가평군', '세부지역_강남구', '세부지역_강동구', '세부지역_강북구', '세부지역_강서구',\n",
       "       '세부지역_고양덕양구', '세부지역_고양일산동구', '세부지역_고양일산서구', '세부지역_과천시', '세부지역_관악구',\n",
       "       '세부지역_광명시', '세부지역_광주시', '세부지역_광진구', '세부지역_구로구', '세부지역_구리시', '세부지역_군포시',\n",
       "       '세부지역_금천구', '세부지역_김포시', '세부지역_남양주시', '세부지역_노원구', '세부지역_도봉구',\n",
       "       '세부지역_동대문구', '세부지역_동두천시', '세부지역_동작구', '세부지역_마포구', '세부지역_부천시',\n",
       "       '세부지역_서대문구', '세부지역_서초구', '세부지역_성남분당구', '세부지역_성남수정구', '세부지역_성남중원구',\n",
       "       '세부지역_성동구', '세부지역_성북구', '세부지역_송파구', '세부지역_수원권선구', '세부지역_수원영통구',\n",
       "       '세부지역_수원장안구', '세부지역_수원팔달구', '세부지역_시흥시', '세부지역_안산단원구', '세부지역_안산상록구',\n",
       "       '세부지역_안성시', '세부지역_안양동안구', '세부지역_안양만안구', '세부지역_양주시', '세부지역_양천구',\n",
       "       '세부지역_양평군', '세부지역_여주시', '세부지역_연천군', '세부지역_영등포구', '세부지역_오산시', '세부지역_용산구',\n",
       "       '세부지역_용인기흥구', '세부지역_용인수지구', '세부지역_용인처인구', '세부지역_은평구', '세부지역_의왕시',\n",
       "       '세부지역_의정부시', '세부지역_이천시', '세부지역_종로구', '세부지역_중구', '세부지역_중랑구', '세부지역_파주시',\n",
       "       '세부지역_평택시', '세부지역_포천시', '세부지역_하남시', '세부지역_화성시'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "GS_with_ohe.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "dbb0c734",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "63680 15920\n",
      "63680 15920\n"
     ]
    }
   ],
   "source": [
    "data = GS_with_ohe.iloc[:,1:]\n",
    "target = GS_with_ohe.iloc[:,:1]\n",
    "x_train, x_valid, y_train, y_valid = train_test_split(data, target, test_size=0.2, shuffle=True, random_state=34)\n",
    "print(len(x_train), len(x_valid))\n",
    "print(len(y_train), len(y_valid))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "7eb68cd9",
   "metadata": {},
   "outputs": [],
   "source": [
    "GS_with_ohe.to_csv(\"/Users/kangminje/Documents/houseprice/GSdata.csv\", mode='w', encoding=\"utf-8-sig\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "0cf2182f",
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "\nAll the 15 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a620b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a721c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a71c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a73ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a73f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a63c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010dfc5a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a4dc350 0x0 + 13057770320\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000125ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000125ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000125ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001260142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000125f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x0000000109904a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030190a350 0x0 + 12911158096\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a6f5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a7f6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a7f10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a813f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a8142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a71101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e124a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a75b350 0x0 + 13060387664\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126cf5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126df6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126df10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126e13f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000126e142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126d1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a705a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000303509350 0x0 + 12940514128\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012ae20b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012af21c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012af1c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012af3ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012af3f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012ae3c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e7c4a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030b688350 0x0 + 13076300624\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000128e56b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000128f57c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000128f520fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000128f74f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000128f752d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000128e7201f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010c857a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030778d350 0x0 + 13010260816\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000129f81b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a082c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a07d0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a09ff9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a0a02d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000129f9d01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010d9afa22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000309908350 0x0 + 13045367632\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000127013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001270142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a8bea22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x00000003034c3350 0x0 + 12940227408\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000125ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000125ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000125ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001260142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000125f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x0000000109904a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030190a350 0x0 + 12911158096\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a620b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a721c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a71c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a73ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a73f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a63c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010dfc5a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a4dc350 0x0 + 13057770320\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a6f5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a7f6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a7f10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a813f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a8142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a71101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e124a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a75b350 0x0 + 13060387664\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126cf5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126df6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126df10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126e13f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000126e142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126d1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a705a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000303509350 0x0 + 12940514128\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012ae20b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012af21c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012af1c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012af3ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012af3f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012ae3c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e7c4a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030b688350 0x0 + 13076300624\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000128e56b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000128f57c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000128f520fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000128f74f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000128f752d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000128e7201f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010c857a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030778d350 0x0 + 13010260816\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000129f81b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a082c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a07d0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a09ff9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a0a02d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000129f9d01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010d9afa22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000309908350 0x0 + 13045367632\n\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 12\u001b[0m\n\u001b[1;32m      7\u001b[0m model \u001b[38;5;241m=\u001b[39m xgb\u001b[38;5;241m.\u001b[39mXGBRegressor(tree_method\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mgpu_hist\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m      8\u001b[0m grid_search \u001b[38;5;241m=\u001b[39m GridSearchCV(estimator\u001b[38;5;241m=\u001b[39mmodel, param_grid\u001b[38;5;241m=\u001b[39mparam, cv\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m, \n\u001b[1;32m      9\u001b[0m                            scoring\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mneg_mean_squared_error\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m     10\u001b[0m                            n_jobs\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m)\n\u001b[0;32m---> 12\u001b[0m \u001b[43mgrid_search\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     13\u001b[0m \u001b[38;5;28mprint\u001b[39m(grid_search\u001b[38;5;241m.\u001b[39mbest_params_)\n\u001b[1;32m     14\u001b[0m \u001b[38;5;28mprint\u001b[39m(grid_search\u001b[38;5;241m.\u001b[39mbest_estimator_)\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_search.py:874\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    868\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_format_results(\n\u001b[1;32m    869\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[1;32m    870\u001b[0m     )\n\u001b[1;32m    872\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[0;32m--> 874\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run_search\u001b[49m\u001b[43m(\u001b[49m\u001b[43mevaluate_candidates\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    876\u001b[0m \u001b[38;5;66;03m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[1;32m    877\u001b[0m \u001b[38;5;66;03m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[1;32m    878\u001b[0m first_test_score \u001b[38;5;241m=\u001b[39m all_out[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtest_scores\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1388\u001b[0m, in \u001b[0;36mGridSearchCV._run_search\u001b[0;34m(self, evaluate_candidates)\u001b[0m\n\u001b[1;32m   1386\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_run_search\u001b[39m(\u001b[38;5;28mself\u001b[39m, evaluate_candidates):\n\u001b[1;32m   1387\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Search all candidates in param_grid\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1388\u001b[0m     \u001b[43mevaluate_candidates\u001b[49m\u001b[43m(\u001b[49m\u001b[43mParameterGrid\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mparam_grid\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_search.py:851\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[0;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[1;32m    844\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m!=\u001b[39m n_candidates \u001b[38;5;241m*\u001b[39m n_splits:\n\u001b[1;32m    845\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m    846\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcv.split and cv.get_n_splits returned \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    847\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minconsistent results. Expected \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    848\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msplits, got \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(n_splits, \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m n_candidates)\n\u001b[1;32m    849\u001b[0m     )\n\u001b[0;32m--> 851\u001b[0m \u001b[43m_warn_or_raise_about_fit_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43merror_score\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    853\u001b[0m \u001b[38;5;66;03m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[1;32m    854\u001b[0m \u001b[38;5;66;03m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[1;32m    855\u001b[0m \u001b[38;5;66;03m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[1;32m    856\u001b[0m \u001b[38;5;66;03m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[1;32m    857\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m callable(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mscoring):\n",
      "File \u001b[0;32m~/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:367\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[0;34m(results, error_score)\u001b[0m\n\u001b[1;32m    360\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m num_failed_fits \u001b[38;5;241m==\u001b[39m num_fits:\n\u001b[1;32m    361\u001b[0m     all_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    362\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mAll the \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    363\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIt is very likely that your model is misconfigured.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    364\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou can try to debug the error by setting error_score=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    365\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    366\u001b[0m     )\n\u001b[0;32m--> 367\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[1;32m    369\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    370\u001b[0m     some_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    371\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mnum_failed_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed out of a total of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    372\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe score on these train-test partitions for these parameters\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    376\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    377\u001b[0m     )\n",
      "\u001b[0;31mValueError\u001b[0m: \nAll the 15 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a620b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a721c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a71c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a73ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a73f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a63c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010dfc5a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a4dc350 0x0 + 13057770320\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000125ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000125ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000125ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001260142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000125f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x0000000109904a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030190a350 0x0 + 12911158096\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a6f5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a7f6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a7f10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a813f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a8142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a71101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e124a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a75b350 0x0 + 13060387664\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126cf5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126df6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126df10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126e13f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000126e142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126d1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a705a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000303509350 0x0 + 12940514128\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012ae20b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012af21c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012af1c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012af3ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012af3f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012ae3c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e7c4a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030b688350 0x0 + 13076300624\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000128e56b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000128f57c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000128f520fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000128f74f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000128f752d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000128e7201f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010c857a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030778d350 0x0 + 13010260816\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000129f81b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a082c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a07d0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a09ff9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a0a02d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000129f9d01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010d9afa22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000309908350 0x0 + 13045367632\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:35] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000127013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001270142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a8bea22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x00000003034c3350 0x0 + 12940227408\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000125ef5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000125ff6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000125ff10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126013f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x00000001260142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000125f1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x0000000109904a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030190a350 0x0 + 12911158096\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a620b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a721c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a71c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a73ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a73f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a63c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010dfc5a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a4dc350 0x0 + 13057770320\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012a6f5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a7f6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a7f10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a813f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a8142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012a71101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e124a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030a75b350 0x0 + 13060387664\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000126cf5b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000126df6c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000126df10fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000126e13f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000126e142d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000126d1101f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010a705a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000303509350 0x0 + 12940514128\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x000000012ae20b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012af21c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012af1c0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012af3ef9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012af3f2d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x000000012ae3c01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010e7c4a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030b688350 0x0 + 13076300624\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000128e56b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x0000000128f57c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x0000000128f520fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x0000000128f74f9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x0000000128f752d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000128e7201f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010c857a22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x000000030778d350 0x0 + 13010260816\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 686, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/sklearn.py\", line 1025, in fit\n    self._Booster = train(\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 620, in inner_f\n    return func(**kwargs)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/training.py\", line 185, in train\n    bst.update(dtrain, i, obj)\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 1918, in update\n    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,\n  File \"/Users/kangminje/opt/anaconda3/envs/AI/lib/python3.10/site-packages/xgboost/core.py\", line 279, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [11:58:36] /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-cpython-38/xgboost/src/gbm/../common/common.h:239: XGBoost version not compiled with GPU support.\nStack trace:\n  [bt] (0) 1   libxgboost.dylib                    0x0000000129f81b15 dmlc::LogMessageFatal::~LogMessageFatal() + 117\n  [bt] (1) 2   libxgboost.dylib                    0x000000012a082c36 xgboost::gbm::GBTree::ConfigureUpdaters() + 534\n  [bt] (2) 3   libxgboost.dylib                    0x000000012a07d0fa xgboost::gbm::GBTree::Configure(std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>> const&) + 1130\n  [bt] (3) 4   libxgboost.dylib                    0x000000012a09ff9d xgboost::LearnerConfiguration::Configure() + 1229\n  [bt] (4) 5   libxgboost.dylib                    0x000000012a0a02d9 xgboost::LearnerImpl::UpdateOneIter(int, std::__1::shared_ptr<xgboost::DMatrix>) + 105\n  [bt] (5) 6   libxgboost.dylib                    0x0000000129f9d01f XGBoosterUpdateOneIter + 143\n  [bt] (6) 7   libffi.8.dylib                      0x000000010d9afa22 ffi_call_unix64 + 82\n  [bt] (7) 8   ???                                 0x0000000309908350 0x0 + 13045367632\n\n\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import GridSearchCV\n",
    "import xgboost as xgb\n",
    "\n",
    "param = {\n",
    "    'learning_rate':[0.05,0.07,0.1],\n",
    "#     'max_depth':[5,6,7],\n",
    "#     'n_estimators':range(550,700,50),\n",
    "#     'colsample_bytree':[0.5,0.7,1],\n",
    "#     'min_child_weight':[1,2,3],\n",
    "#     'subsample':[0.6,0.7,0.8]\n",
    "}\n",
    "model = xgb.XGBRegressor(tree_method='gpu_hist')\n",
    "grid_search = GridSearchCV(estimator=model, param_grid=param, cv=5, \n",
    "                           scoring='neg_mean_squared_error',\n",
    "                           n_jobs=-1)\n",
    "\n",
    "grid_search.fit(x_train, y_train)\n",
    "print(grid_search.best_params_)\n",
    "print(grid_search.best_estimator_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a64f362",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
    "pred_train = grid_search.predict(x_train)\n",
    "pred_val = grid_search.predict(x_valid)\n",
    "\n",
    "print('train mae score: ', mean_absolute_error(y_train, pred_train))\n",
    "print('val mae score:', mean_absolute_error(y_valid, pred_val))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "57621cd7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
